version: "3.7"

services:
  notifications-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: notifications-service
    container_name: notifications-service
    command: npm run start
    volumes:
      - ./:/app
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    depends_on:
      - redis
    networks:
      - good-food

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - good-food

networks:
  good-food:
    external: true
