apiVersion: apps/v1
kind: Deployment
metadata:
    name: notifications-service
    labels:
        app: notifications-service
spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
        matchLabels:
            app: notifications-service
    template:
        metadata:
            labels:
                app: notifications-service
        spec:
            imagePullSecrets:
                - name: scw-registry-secret
            containers:
                - name: notifications-service
                  image: rg.fr-par.scw.cloud/good-food-container-registry/notifications-service:6c1cdf13f2d8acecfd40a2528f052db17975f9de
                  imagePullPolicy: Always
                  command: ["/bin/sh", "-c"]
                  args:
                      - npx ts-node src/index.ts
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "10m"
                      limits:
                          memory: "256Mi"
                          cpu: "100m"
                  envFrom:
                      - configMapRef:
                            name: notifications-service-config
                      - secretRef:
                            name: rabbitmq-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: notifications-consumer
    labels:
        app: notifications-consumer
spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
        matchLabels:
            app: notifications-consumer
    template:
        metadata:
            labels:
                app: notifications-consumer
        spec:
            imagePullSecrets:
                - name: scw-registry-secret
            containers:
                - name: notifications-consumer
                  image: rg.fr-par.scw.cloud/good-food-container-registry/notifications-service:6c1cdf13f2d8acecfd40a2528f052db17975f9de
                  imagePullPolicy: Always
                  command: ["/bin/sh", "-c"]
                  args:
                      - npx ts-node src/consumer/handler.ts
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "10m"
                      limits:
                          memory: "256Mi"
                          cpu: "100m"
                  envFrom:
                      - configMapRef:
                            name: notifications-service-config
                      - secretRef:
                            name: rabbitmq-secret
---
apiVersion: v1
kind: Service
metadata:
    name: notifications-service
spec:
    selector:
        app: notifications-service
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: notifications-service-config
data:
    NODE_ENV: "production"
    PORT: "8080"
    RABBITMQ_HOST: "rabbitmq"
    RABBITMQ_PORT: "5672"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
